// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineForestAPI.Data;

#nullable disable

namespace OnlineForestAPI.Migrations
{
    [DbContext(typeof(ForestOnlineDbContext))]
    [Migration("20250409105556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineForestAPI.Models.Land", b =>
                {
                    b.Property<int>("LandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandId"));

                    b.Property<int>("LandCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LandSpecificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastPlanted")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LandId");

                    b.HasIndex("LandCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Lands");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.LandCategory", b =>
                {
                    b.Property<int>("LandCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandCategoryId"));

                    b.Property<int>("LandPrice")
                        .HasColumnType("int");

                    b.Property<int>("MaxSlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LandCategoryId");

                    b.ToTable("LandCategories");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.TokenEarn", b =>
                {
                    b.Property<int>("TokenEarnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenEarnId"));

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.Property<int>("TreeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenEarnId");

                    b.HasIndex("TreeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TokenEarns");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.Tree", b =>
                {
                    b.Property<int>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreeId"));

                    b.Property<bool>("IsHarvest")
                        .HasColumnType("bit");

                    b.Property<int?>("LandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TokenEarnId")
                        .HasColumnType("int");

                    b.Property<int>("TreeCategoryId")
                        .HasColumnType("int");

                    b.HasKey("TreeId");

                    b.HasIndex("LandId");

                    b.HasIndex("TreeCategoryId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.TreeCategory", b =>
                {
                    b.Property<int>("TreeCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreeCategoryId"));

                    b.Property<int>("GrowthTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TreePrice")
                        .HasColumnType("int");

                    b.HasKey("TreeCategoryId");

                    b.ToTable("TreeCategories");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalTokenEarn")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.Land", b =>
                {
                    b.HasOne("OnlineForestAPI.Models.LandCategory", "LandCategory")
                        .WithMany("Lands")
                        .HasForeignKey("LandCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineForestAPI.Models.User", null)
                        .WithMany("Lands")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandCategory");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.TokenEarn", b =>
                {
                    b.HasOne("OnlineForestAPI.Models.Tree", "Tree")
                        .WithOne("TokenEarn")
                        .HasForeignKey("OnlineForestAPI.Models.TokenEarn", "TreeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineForestAPI.Models.User", null)
                        .WithMany("TokenEarnings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.Tree", b =>
                {
                    b.HasOne("OnlineForestAPI.Models.Land", "Land")
                        .WithMany("Trees")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineForestAPI.Models.TreeCategory", "TreeCategory")
                        .WithMany("Trees")
                        .HasForeignKey("TreeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");

                    b.Navigation("TreeCategory");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.Land", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.LandCategory", b =>
                {
                    b.Navigation("Lands");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.Tree", b =>
                {
                    b.Navigation("TokenEarn")
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineForestAPI.Models.TreeCategory", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("OnlineForestAPI.Models.User", b =>
                {
                    b.Navigation("Lands");

                    b.Navigation("TokenEarnings");
                });
#pragma warning restore 612, 618
        }
    }
}
